### ISSUE TITLE
Use case diagram - Library management system

### ISSUE THREAD

**Issue by karanbhatia116** [karanbhatia116/G_14-Workflow-management-system#1]

**Comment by karanbhatia116** [comment]
[IT314_Lab7_Ques1_useCase.pdf](https://github.com/karanbhatia116/G_14-Workflow-management-system/files/6252412/IT314_Lab7_Ques1_useCase.pdf)
Added Lab 7 Ques1 use case diagram

**Comment by AlayKharadi** [comment]
[IT314_Lab7_Ques1_useCase.pdf](https://github.com/karanbhatia116/G_14-Workflow-management-system/files/6252418/IT314_Lab7_Ques1_useCase.pdf)
Added Lab 7 Question 1 diagram

**Comment by AlayKharadi** [comment]
[IT314_Lab7_Ques1_useCase.pdf](https://github.com/karanbhatia116/G_14-Workflow-management-system/files/6252423/IT314_Lab7_Ques1_useCase.pdf)
Added lab7 Question 1 useCase diagram
