### ISSUE TITLE
Sequence diagram for issueBook

### ISSUE THREAD

**Issue by karanbhatia116** [karanbhatia116/G_14-Workflow-management-system#2]

**Comment by Dhruvik07** [comment]
https://docs.google.com/document/d/1qJbw_KsQMJLyTyjp0f16oUOlHvLRh2oEBhNT-dQhzy0/edit?usp=sharing

**Comment by Hiren2705** [comment]
[IT314_G14_Lab7_Q2.pdf](https://github.com/karanbhatia116/G_14-Workflow-management-system/files/6252404/IT314_G14_Lab7_Q2.pdf)

**Comment by darshilrana8** [comment]
[IT314_G14_Lab7_Q1_sequence_diagram.pdf](https://github.com/karanbhatia116/G_14-Workflow-management-system/files/6252410/IT314_G14_Lab7_Q1_sequence_diagram.pdf)

**Comment by Dhruvik07** [comment]
[IT314_G14_Lab7_Q1_The_Sequence_Diagram.pdf](https://github.com/karanbhatia116/G_14-Workflow-management-system/files/6252413/IT314_G14_Lab7_Q1_The_Sequence_Diagram.pdf)

**Comment by Parth48** [comment]
[IT314_G14_Lab7_SequenceDiagram.docx](https://github.com/karanbhatia116/G_14-Workflow-management-system/files/6252535/IT314_G14_Lab7_SequenceDiagram.docx)
