### ISSUE TITLE
Analysis object diagram for the “issueBook”

### ISSUE THREAD

**Issue by karanbhatia116** [karanbhatia116/G_14-Workflow-management-system#3]

**Comment by shivani-nandani** [comment]
q1 part 3 for lab7
[IT-314_G14_lab7_Q3.pdf](https://github.com/karanbhatia116/G_14-Workflow-management-system/files/6252384/IT-314_G14_lab7_Q3.pdf)

**Comment by Jiyapatel105** [comment]
https://docs.google.com/document/d/1xyqMYapIejnkquQJi4wLXNQ0pryt2H6mefeCqvQyLac/edit?usp=sharing
